import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/ThemeProvider/theme-provider";
import Header from "@/components/header";
import {ClerkProvider} from "@clerk/nextjs";

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
            <body
                className={`${inter.className}`}
            >
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange>
                {/*Header*/}
                <Header/>
                <main className={"min-h-screen"}>{children}</main>
                {/*Footer*/}
                <footer className={"bg-blue-50 dark:bg-background dark:text-gray-200  text-gray-900 py-12"}>
                    <div className={"container mx-auto px-4 justify-center items-center flex"}>
                        Made with ❤️ by Parth
                    </div>
                </footer>
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    );
}
